disabled_rules:
    - file_length
    - cyclomatic_complexity
    - trailing_comma
    - opening_brace
    - identifier_name
    - function_parameter_count
    - nesting
    - type_body_length
    - function_body_length
    - non_optional_string_data_conversion
excluded:
  - .build